add_newline = false

[cmd_duration]
disabled = true

[kubernetes]
disabled = false

[ruby]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[package]
disabled = true

[terraform]
disabled = true

[aws.region_aliases]
us-east-1 = "use1"
us-west-2 = "usw2"
eu-central-1 = "euc1"
eu-west-1 = "euw1"
