# -*- mode: shell-script -*-

S76_TOUCHPAD="SynPS/2 Synaptics TouchPad"

# this must be run before xmodmap
# see https://unix.stackexchange.com/questions/403962/xmodmap-not-working-on-startup
echo "run setxkbmap" >&2
# remap caps lock to ctrl
setxkbmap -option caps:ctrl_modifier

echo "run xmodmap" >&2
# thinkpad
# Remap print screen to Super_R
xmodmap -e 'keycode 107 = Super_R'

# system76
# Remap menu to Super_R
xmodmap -e 'keycode 135 = Super_R'

if xinput list "$S76_TOUCHPAD" >/dev/null 2>/dev/null; then
  echo "configure system76 touchpad" >&2
  xinput set-prop "$S76_TOUCHPAD" "libinput Tapping Enabled" 1
  xinput set-prop "$S76_TOUCHPAD" "libinput Accel Speed" 0.8
fi

exec i3
